spring:


  datasource:
    url: jdbc:h2:mem:customer
    password: customer
    username: customer
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true

  cloud:
    config:
      uri: http://localhost:9097
      import-check:
        enabled: true
  config:
    import: "optional:configserver:http://localhost:9097/"
server:
  port: 9091

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health


resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      listHotel:
          register-health-indicator: true
          event-consumer-buffer-size: 10
          failure-rate-threshold: 50
          minimum-number-of-calls: 5
          automatic-transition-from-open-to-half-open-enabled: true
          wait-duration-in-open-state: 6s
          permitted-number-of-calls-in-half-open-state: 3
          sliding-window-size: 10
          sliding-window-type: COUNT_BASED



